# Needs to publish both amd64 and 386
- repo: kubeaudit
  org: Shopify

# Published multiple for each platform
- repo: hugo
  org: gohugoio

# Assets has path in tar
- repo: glide
  org: Masterminds

# ## Assets has path in tar.. :s
- repo: aks-engine
  org: Azure

# Assets has both zip and tar and win exe not in tar.. :s
- repo: kompose
  org: kubernetes

- repo: skaffold
  org: GoogleContainerTools

- repo: chartmuseum
  org: helm

- repo: k9s
  org: derailed

- repo: saml2aws
  org: Versent

- repo: cli
  org: gobuffalo
  name: buffalo

- repo: istio
  org: istio
  name: istioctl

- repo: brigade
  org: Azure
  name: brig
  arch: amd64

- repo: bicep
  org: Azure
  arch: x64

- repo: helmfile
  org: roboll

- repo: cri-tools
  org: kubernetes-sigs
  name: crictl

- repo: cri-tools
  org: kubernetes-sigs
  name: critest

- repo: cluster-api
  org: kubernetes-sigs
  name: clusterctl

- repo: fission
  org: fission

- repo: kubebuilder
  org: kubernetes-sigs
  arch: amd64

- repo: jwt-cli
  org: mike-engel
  arch: ""

- repo: eksctl
  org: weaveworks

- repo: stern
  org: wercker

- repo: minectl
  org: dirien

- repo: k0sctl
  org: k0sproject  

- repo: helm
  org: helm

- repo: cosign
  org: sigstore

- repo: argo-cd
  name: argocd
  org: argoproj

- repo: polaris
  org: FairwindsOps
  arch: amd64

- repo: nova
  org: FairwindsOps
  arch: amd64

- repo: sealed-secrets
  name: kubeseal
  org: bitnami-labs

- repo: flux
  name: fluxctl
  org: fluxcd

- repo: flux2
  name: flux
  org: fluxcd

- repo: jx
  org: jenkins-x

- repo: k3d
  org: rancher

- repo: cli
  org: rancher
  name: rancher

- repo: cli
  org: cli
  name: gh

- repo: golangci-lint
  org: golangci

- repo: minikube
  org: kubernetes
  arch: amd64

- repo: anycable-go
  org: anycable
  arch: amd64

- repo: oras
  org: deislabs
  arch: amd64

- repo: tilt
  org: tilt-dev
  arch: x64

- repo: terraform-docs
  org: terraform-docs
  arch: amd64

- repo: yaegi
  org: traefik
  arch: amd64

- repo: terragrunt
  org: gruntwork-io
  arch: amd64

- repo: policy-hub-cli
  org: policy-hub
  arch: x64

- repo: osm
  org: openservicemesh
  arch: amd64

- repo: krustlet
  org: deislabs
  arch: amd64

- repo: octant
  org: vmware-tanzu
  arch: 64bit

- repo: cloudsql-proxy
  org: GoogleCloudPlatform
  arch: amd64
  name: cloud_sql_proxy

- repo: kubernetes
  org: kubernetes
  name: kubectl

- repo: go
  org: golang

- repo: vagrant
  org: hashicorp
  arch: amd64

- repo: kube-no-trouble
  org: doitintl
  arch: amd64

- repo: gitleaks
  org: zricethezav
  arch: amd64

- repo: infracost
  org: infracost
  arch: amd64

- repo: act
  org: nektos

- repo: arkade
  org: alexellis

- repo: chart-testing
  org: helm

- repo: conftest
  org: open-policy-agent

- repo: gloo
  org: solo-io
  name: glooctl

- repo: terraform
  org: hashicorp
  arch: amd64

- repo: packer
  org: hashicorp
  arch: amd64

- repo: vault
  org: hashicorp
  arch: amd64

- repo: kustomize
  org: kubernetes-sigs

- repo: tfsec
  org: tfsec
  arch: amd64

- repo: wasmtime
  org: bytecodealliance
  arch: amd64

- repo: uplift
  org: gembaadvantage

- repo: codecommit-sign
  org: gembaadvantage

- repo: git-remote-codecommit
  org: gembaadvantage

- repo: goreleaser
  org: goreleaser

- repo: berglas
  org: GoogleCloudPlatform

- repo: kubectx
  org: ahmetb
  name: kubectx

- repo: kubectx
  org: ahmetb
  name: kubens

- repo: yq
  org: mikefarah

# Release not following semantic versioning
# - repo: linkerd2
#   org: linkerd
#   name: linkerd

# Missing windows releases
# - repo: letitgo
#   org: NoUseFreak

# Zip not published on jetbrains https://github.com/fishworks/fish-food/issues/323
# - repo: delve
#   org: go-delve

